const { contextBridge, ipcRenderer, webFrame, webUtils } = require('electron');

contextBridge.exposeInMainWorld('onyx', {
  platform: process.platform,
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  openRecent: (p) => ipcRenderer.invoke('open-recent', p),
  openPath: (p) => ipcRenderer.invoke('open-path', p),
  pathForFile: (file) => { try { return webUtils.getPathForFile(file); } catch { return ''; } },
  loadDemo: () => ipcRenderer.invoke('load-demo'),
  rescan: () => ipcRenderer.invoke('rescan'),
  organize: (strategy) => ipcRenderer.invoke('organize', strategy),
  apply: (items) => ipcRenderer.invoke('apply-plan', items),
  undo: () => ipcRenderer.invoke('undo'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (patch) => ipcRenderer.invoke('save-settings', patch),
  replaceSetting: (section, key, value) => ipcRenderer.invoke('replace-settings', { section, key, value }),
  resetSettings: (which) => ipcRenderer.invoke('reset-settings', which),
  exportSettings: () => ipcRenderer.invoke('export-settings'),
  importSettings: () => ipcRenderer.invoke('import-settings'),
  testAi: () => ipcRenderer.invoke('test-ai'),
  reveal: (rel) => ipcRenderer.invoke('reveal', rel),
  copyText: (t) => ipcRenderer.invoke('copy-text', t),
  setTitleBar: (c) => ipcRenderer.invoke('set-titlebar', c),
  setZoom: (z) => { try { webFrame.setZoomFactor(z); } catch { /* ignore */ } },
  onProgress: (cb) => ipcRenderer.on('organize-progress', (e, p) => cb(p)),
  // tags and the library
  tagsEdit: (paths, add, remove) => ipcRenderer.invoke('tags-edit', { paths, add, remove }),
  tagsRename: (from, to) => ipcRenderer.invoke('tags-rename', { from, to }),
  tagsDelete: (name) => ipcRenderer.invoke('tags-delete', name),
  tagsColor: (name, color) => ipcRenderer.invoke('tags-color', { name, color }),
  tagsSaved: (list) => ipcRenderer.invoke('tags-saved', list),
  tagsClearAuto: (paths) => ipcRenderer.invoke('tags-clear-auto', paths),
  tagsAuto: (opts) => ipcRenderer.invoke('tags-auto', opts),
  tagsCancel: () => ipcRenderer.invoke('tags-cancel'),
  tagsRemoveAuto: (name) => ipcRenderer.invoke('tags-remove-auto', name),
  onTagProgress: (cb) => ipcRenderer.on('tag-progress', (e, p) => cb(p)),
  openFile: (rel) => ipcRenderer.invoke('open-file', rel),
  thumb: (rel, size) => ipcRenderer.invoke('file-thumb', { rel, size }),
  // browsing drives and other big locations
  listDir: (rel) => ipcRenderer.invoke('list-dir', rel),
  searchDir: (rel, query, limit) => ipcRenderer.invoke('search-dir', { rel, query, limit }),
  listPlaces: () => ipcRenderer.invoke('list-places'),
});
