const { contextBridge, ipcRenderer, webFrame, webUtils } = require('electron');

contextBridge.exposeInMainWorld('onyx', {
  platform: process.platform,
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  openRecent: (p) => ipcRenderer.invoke('open-recent', p),
  openPath: (p) => ipcRenderer.invoke('open-path', p),
  pathForFile: (file) => { try { return webUtils.getPathForFile(file); } catch { return ''; } },
  loadDemo: () => ipcRenderer.invoke('load-demo'),
  rescan: () => ipcRenderer.invoke('rescan'),
  organize: (strategy) => ipcRenderer.invoke('organize', strategy),
  apply: (items) => ipcRenderer.invoke('apply-plan', items),
  undo: () => ipcRenderer.invoke('undo'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (patch) => ipcRenderer.invoke('save-settings', patch),
  replaceSetting: (section, key, value) => ipcRenderer.invoke('replace-settings', { section, key, value }),
  resetSettings: (which) => ipcRenderer.invoke('reset-settings', which),
  exportSettings: () => ipcRenderer.invoke('export-settings'),
  importSettings: () => ipcRenderer.invoke('import-settings'),
  testAi: () => ipcRenderer.invoke('test-ai'),
  reveal: (rel) => ipcRenderer.invoke('reveal', rel),
  copyText: (t) => ipcRenderer.invoke('copy-text', t),
  setTitleBar: (c) => ipcRenderer.invoke('set-titlebar', c),
  setZoom: (z) => { try { webFrame.setZoomFactor(z); } catch { /* ignore */ } },
  onProgress: (cb) => ipcRenderer.on('organize-progress', (e, p) => cb(p)),
  // tags and the library
  tagsEdit: (paths, add, remove) => ipcRenderer.invoke('tags-edit', { paths, add, remove }),
  tagsRename: (from, to) => ipcRenderer.invoke('tags-rename', { from, to }),
  tagsDelete: (name) => ipcRenderer.invoke('tags-delete', name),
  tagsColor: (name, color) => ipcRenderer.invoke('tags-color', { name, color }),
  tagsSaved: (list) => ipcRenderer.invoke('tags-saved', list),
  tagsClearAuto: (paths) => ipcRenderer.invoke('tags-clear-auto', paths),
  tagsAuto: (opts) => ipcRenderer.invoke('tags-auto', opts),
  tagsCancel: () => ipcRenderer.invoke('tags-cancel'),
  tagsRemoveAuto: (name) => ipcRenderer.invoke('tags-remove-auto', name),
  onTagProgress: (cb) => ipcRenderer.on('tag-progress', (e, p) => cb(p)),
  openFile: (rel) => ipcRenderer.invoke('open-file', rel),
  thumb: (rel, size) => ipcRenderer.invoke('file-thumb', { rel, size }),
  // browsing drives and other big locations
  listDir: (rel) => ipcRenderer.invoke('list-dir', rel),
  searchDir: (rel, query, limit) => ipcRenderer.invoke('search-dir', { rel, query, limit }),
  listPlaces: () => ipcRenderer.invoke('list-places'),
  // file operations, like File Explorer
  fsNew: (dir, kind) => ipcRenderer.invoke('fs-new', { dir, kind }),
  fsRename: (rel, name) => ipcRenderer.invoke('fs-rename', { rel, name }),
  fsRenameMany: (rels, name) => ipcRenderer.invoke('fs-rename-many', { rels, name }),
  fsTrash: (rels) => ipcRenderer.invoke('fs-trash', rels),
  fsDelete: (rels) => ipcRenderer.invoke('fs-delete', rels),
  fsPlanPaste: (sources, dest, mode) => ipcRenderer.invoke('fs-plan-paste', { sources, dest, mode }),
  fsPaste: (opts) => ipcRenderer.invoke('fs-paste', opts),
  fsCancel: () => ipcRenderer.invoke('fs-cancel'),
  fsUndo: () => ipcRenderer.invoke('fs-undo'),
  fsUndoLabel: () => ipcRenderer.invoke('fs-undo-label'),
  fsClipSet: (rels, effect) => ipcRenderer.invoke('fs-clip-set', { rels, effect }),
  fsClipGet: () => ipcRenderer.invoke('fs-clip-get'),
  fsProperties: (rels) => ipcRenderer.invoke('fs-properties', rels),
  fsOpenWith: (rel) => ipcRenderer.invoke('fs-open-with', rel),
  fsShellMenu: (rels) => ipcRenderer.invoke('fs-shell-menu', rels),
  fsTerminal: (rel) => ipcRenderer.invoke('fs-terminal', rel),
  fsRunAdmin: (rel) => ipcRenderer.invoke('fs-run-admin', rel),
  fsCompress: (rels) => ipcRenderer.invoke('fs-compress', rels),
  fsExtract: (rel) => ipcRenderer.invoke('fs-extract', rel),
  fsShortcut: (rels) => ipcRenderer.invoke('fs-shortcut', rels),
  fsWatch: (rel) => ipcRenderer.invoke('fs-watch', rel),
  startDrag: (rels) => ipcRenderer.send('start-drag', rels),
  // the viewer
  fileUrl: (rel, v) => 'onyx-file://local/' + String(rel).split('/').map(encodeURIComponent).join('/') + (v ? '?v=' + encodeURIComponent(v) : ''),
  fileText: (rel) => ipcRenderer.invoke('file-text', rel),
  extList: () => ipcRenderer.invoke('ext-list'),
  extOpenFolder: () => ipcRenderer.invoke('ext-open-folder'),
  onDragDone: (cb) => ipcRenderer.on('drag-done', () => cb()),
  onFileOpProgress: (cb) => ipcRenderer.on('fileop-progress', (e, p) => cb(p)),
  onFsChanged: (cb) => ipcRenderer.on('fs-changed', (e, p) => cb(p)),
});
